// Node test suite for Model.js — plain assert, no framework.
// Run: node test-model.js
const assert = require("assert")
const M = require("./Model.js")

const eq = (a, b, msg) => assert.strictEqual(a, b, msg)
const ok = (v, msg) => assert.ok(v, msg)
const has = (haystack, needle, msg) => assert.ok(String(haystack).includes(needle), msg)

// --- addresses -------------------------------------------------------------
eq(M.endpointFromURL("http://10.0.0.5:7890"), "10.0.0.5:7890", "plain http url")
eq(M.endpointFromURL("https://user:pw@10.0.0.5:7890/"), "10.0.0.5:7890", "userinfo and path are dropped")
eq(M.endpointFromURL("socks5h://10.0.0.5:7890"), "10.0.0.5:7890", "socks scheme is dropped")
eq(M.endpointFromURL(""), "", "empty url")
eq(M.endpointFromURL(null), "", "null url does not throw")

ok(M.isAddress("10.0.0.5:7890"), "host:port is an address")
ok(M.isAddress("localhost:7890"), "hostnames are addresses")
ok(!M.isAddress("10.0.0.5"), "missing port is not an address")
ok(!M.isAddress("10.0.0.5:port"), "non numeric port is not an address")
ok(!M.isAddress(""), "empty string is not an address")

eq(M.normalizeAddress("10.0.0.9:1080", "1.1.1.1:1"), "10.0.0.9:1080", "valid address wins")
eq(M.normalizeAddress("garbage", "1.1.1.1:1"), "1.1.1.1:1", "invalid address falls back")
eq(M.normalizeAddress(null, "1.1.1.1:1"), "1.1.1.1:1", "null falls back")

// --- interval clamping -----------------------------------------------------
eq(M.checkIntervalSeconds(undefined), 60, "default interval")
eq(M.checkIntervalSeconds("120"), 120, "string numbers are accepted")
eq(M.checkIntervalSeconds(5), 30, "too small is raised to the minimum")
eq(M.checkIntervalSeconds(99999), 3600, "too large is capped")
eq(M.checkIntervalSeconds("nonsense"), 60, "garbage falls back to the default")

// --- env file parsing ------------------------------------------------------
const envOn = [
  "# Generated by proxyctl. Use proxyctl on/off/restore to change.",
  "http_proxy=http://10.10.10.111:7890",
  "https_proxy=http://10.10.10.111:7890",
  "all_proxy=socks5h://10.10.10.111:7890",
  "no_proxy=localhost,127.0.0.1,::1"
].join("\n")

const on = M.parseEnvFile(envOn)
eq(on.on, true, "managed env file means the proxy is on")
eq(on.endpoint, "10.10.10.111:7890", "endpoint comes from http_proxy")
eq(on.entries, 2, "http_proxy and https_proxy both count")

const off = M.parseEnvFile("")
eq(off.on, false, "missing file means direct")
eq(off.endpoint, "", "no endpoint while direct")
eq(M.parseEnvFile(null).on, false, "null text does not throw")
eq(M.parseEnvFile("no_proxy=localhost").on, false, "a no_proxy-only file is not a proxy")
eq(M.parseEnvFile("HTTP_PROXY=http://10.0.0.5:8080").endpoint, "10.0.0.5:8080", "uppercase keys work")

// --- probe parsing ---------------------------------------------------------
const good = M.parseProbe(0, "204 0.087\n", "")
eq(good.ok, true, "204 is a healthy probe")
eq(good.ms, 87, "seconds are converted to milliseconds")
eq(good.error, "", "healthy probe has no error")

eq(M.parseProbe(0, "200 1.5", "").ms, 1500, "200 is healthy too")
eq(M.parseProbe(0, "502 0.2", "").ok, false, "5xx is not healthy")
eq(M.parseProbe(0, "502 0.2", "").error, "HTTP 502", "failure carries the code")

const timedOut = M.parseProbe(28, "", "curl: (28) Connection timed out after 8000 milliseconds")
eq(timedOut.ok, false, "curl timeout is a failure")
has(timedOut.error, "timed out", "curl's own message is surfaced")

const noEndpoint = M.parseProbe(7, "", "")
eq(noEndpoint.ok, false, "curl exit 7 is a failure")
eq(noEndpoint.error, "curl exit 7", "missing stderr still names the exit code")
eq(M.parseProbe(0, "", "").ok, false, "empty output is not healthy")

// --- probe command ---------------------------------------------------------
const args = M.probeArgs("10.10.10.111:7890")
eq(args[0], "curl", "probe runs curl")
eq(args.indexOf("-x") >= 0, true, "probe uses an explicit proxy")
eq(args[args.indexOf("-x") + 1], "http://10.10.10.111:7890", "proxy flag carries the endpoint")
eq(args[args.indexOf("--noproxy") + 1], "", "no_proxy is emptied for the probe")
eq(args[args.length - 1], M.PROBE_URL, "probe target is last")
has(args[args.indexOf("-w") + 1], "%{http_code}", "probe formats the status code")

// --- toggle command --------------------------------------------------------
const onArgs = M.toggleArgs(false, "10.10.10.111:7890", "/home/u/.local/bin/proxyctl")
eq(onArgs.length, 4, "enable passes the address")
eq(onArgs[1], "on", "enable uses proxyctl on")
eq(onArgs[3], "10.10.10.111:7890", "enable carries the address")
eq(M.toggleArgs(true, "10.10.10.111:7890", "/bin/proxyctl").join(" "), "/bin/proxyctl off", "disable is proxyctl off")
eq(M.toggleArgs(false, "garbage", "/bin/proxyctl").length, 0, "bad address refuses to run")
eq(M.toggleArgs(false, "10.0.0.5:7890", "").length, 0, "missing binary refuses to run")

// --- display ---------------------------------------------------------------
eq(M.barLabel(false, false, null), "off", "off label")
eq(M.barLabel(true, true, null), "\u2026", "busy label")
eq(M.barLabel(true, false, null), "on", "on without a probe yet")
eq(M.barLabel(true, false, { ok: true, ms: 87 }), "on 87ms", "latency label")
eq(M.barLabel(true, false, { ok: true, ms: -1 }), "on", "healthy without timing")
eq(M.barLabel(true, false, { ok: false, ms: -1 }), "on !", "failure marker")

eq(M.healthOk({ ok: true }), true, "healthOk true")
eq(M.healthOk(null), false, "healthOk false when unknown")
eq(M.healthFailed(null), false, "unknown is not a failure")
eq(M.healthFailed({ ok: false }), true, "failed is a failure")

eq(M.clockTime(0).length, 8, "clock time is HH:MM:SS shaped")
eq(M.clockTime("nonsense"), "", "invalid timestamps render empty")

const onTip = M.tooltipText({
  on: true, busy: false, endpoint: "10.10.10.111:7890",
  health: { ok: true, ms: 87, at: Date.now() }, probeEnabled: true
})
has(onTip, "Proxy on 10.10.10.111:7890", "tooltip names the endpoint")
has(onTip, "87ms", "tooltip shows the latency")
has(onTip, "left-click opens the panel", "tooltip points at the panel")

const offTip = M.tooltipText({ on: false, configured: "10.10.10.111:7890", health: null, probeEnabled: true })
has(offTip, "Proxy off", "off tooltip")
has(offTip, "enable 10.10.10.111:7890 from the panel", "off tooltip names the address the panel would enable")
has(offTip, "left-click opens the panel", "off tooltip points at the panel")

const failTip = M.tooltipText({
  on: true, busy: false, endpoint: "10.0.0.5:7890",
  health: { ok: false, ms: -1, error: "curl: (28) timed out", at: 0 }, probeEnabled: true
})
has(failTip, "last check failed", "failure tooltip")
has(failTip, "timed out", "failure tooltip carries the reason")

const quietTip = M.tooltipText({ on: true, busy: false, endpoint: "10.0.0.5:7890", health: null, probeEnabled: false })
has(quietTip, "health check off", "probe disabled is stated")

const errorTip = M.tooltipText({ on: false, configured: "10.0.0.5:7890", health: null, probeEnabled: true, error: "proxyctl exit 1" })
has(errorTip, "proxyctl exit 1", "toggle errors surface in the tooltip")

has(M.tooltipText({ on: true, endpoint: "10.0.0.5:7890", health: null, probeEnabled: true, tun: "running" }),
  "TUN on", "tooltip mentions a running TUN")
ok(!M.tooltipText({ on: true, endpoint: "10.0.0.5:7890", health: null, probeEnabled: true, tun: "stopped" })
  .includes("TUN on"), "stopped TUN stays out of the tooltip")

// --- exit IP ---------------------------------------------------------------
const ipArgs = M.exitIpArgs("10.10.10.111:7890")
eq(ipArgs[0], "curl", "exit-ip probe runs curl")
eq(ipArgs[ipArgs.length - 1], M.PROBE_EXIT_IP_URL, "exit-ip probe asks ipify")
eq(ipArgs[ipArgs.indexOf("-x") + 1], "http://10.10.10.111:7890", "exit-ip probe goes through the proxy")

eq(M.cleanExitIp("155.117.84.152\n"), "155.117.84.152", "ipv4 is trimmed")
eq(M.cleanExitIp("2001:db8::1"), "2001:db8::1", "ipv6 is kept")
eq(M.cleanExitIp("<html>error</html>"), "", "an error page is not an address")
eq(M.cleanExitIp(""), "", "empty body is not an address")
eq(M.cleanExitIp(null), "", "null does not throw")
eq(M.cleanExitIp("999"), "", "a bare number is not an address")
eq(M.cleanExitIp("1.2.3.4.5"), "", "a malformed ipv4 is rejected")
eq(M.cleanExitIp("x".repeat(60)), "", "absurdly long bodies are rejected")

// --- panel lines -----------------------------------------------------------
eq(M.healthLine(false, false, null, true), "proxy is off", "panel health when off")
eq(M.healthLine(true, true, null, true), "checking\u2026", "panel health while probing")
eq(M.healthLine(true, false, { ok: true, ms: 87, at: 0 }, false), "health check disabled in settings", "panel health with the probe off")
eq(M.healthLine(true, false, null, true), "not checked yet", "panel health before the first probe")
has(M.healthLine(true, false, { ok: true, ms: 87, at: 0 }, true), "87ms", "panel health shows the latency")
has(M.healthLine(true, false, { ok: false, ms: -1, error: "timed out", at: 0 }, true), "failed: timed out", "panel health shows the failure")

eq(M.exitIpLine(false, false, ""), "\u2014", "no exit ip while off")
eq(M.exitIpLine(true, true, ""), "checking\u2026", "exit ip while probing")
eq(M.exitIpLine(true, false, "155.117.84.152"), "155.117.84.152", "exit ip is shown")
eq(M.exitIpLine(true, false, ""), "\u2014", "exit ip placeholder when unknown")

const summary = M.statusSummary({
  on: true, endpoint: "10.10.10.111:7890", health: { ok: true, ms: 87, at: 0 },
  exitIp: "155.117.84.152", probeEnabled: true
})
has(summary, "Proxy (proxyctl): on", "summary states the state")
has(summary, "Endpoint: 10.10.10.111:7890", "summary states the endpoint")
has(summary, "Exit IP: 155.117.84.152", "summary states the exit ip")
eq(summary.split("\n").length, 4, "summary is a four-line block while on")

const offSummary = M.statusSummary({ on: false, configured: "10.10.10.111:7890" })
has(offSummary, "Proxy (proxyctl): off", "off summary")
eq(offSummary.split("\n").length, 2, "off summary stays short")

// --- TUN -------------------------------------------------------------------
eq(M.tunArgs(true, "10.10.10.111:7890", "/bin/proxyctl").join(" "),
  "/bin/proxyctl tun on --address 10.10.10.111:7890", "enabling TUN passes the upstream")
eq(M.tunArgs(false, "", "/bin/proxyctl").join(" "), "/bin/proxyctl tun off", "disabling TUN")
eq(M.tunArgs(true, "garbage", "/bin/proxyctl").length, 0, "TUN refuses a bad upstream")
eq(M.tunArgs(true, "10.0.0.5:7890", "").length, 0, "TUN needs a binary")
eq(M.statusArgs("/bin/proxyctl").join(" "), "/bin/proxyctl status", "status args")
eq(M.toolsArgs("/bin/proxyctl").join(" "), "/bin/proxyctl tools list", "tools args")

// --- proxyctl status parsing (real output shapes) ---------------------------
const statusOn = [
  "=== 系统代理 ===",
  "HTTP   代理已启用: http://10.10.10.111:7890",
  "HTTPS  代理已启用: http://10.10.10.111:7890",
  "PAC    代理: 未启用",
  "",
  "=== Git 全局代理 ===",
  "  http.proxy  = http://10.10.10.111:7890",
  "  https.proxy = http://10.10.10.111:7890",
  "",
  "=== Omarchy 系统设置 ===",
  "终端代理环境变量:",
  "  （未设置）",
  "会话环境文件:",
  "  存在: /home/alex/.config/environment.d/proxy.conf",
  "Chromium/Chrome flags:",
  "  /home/alex/.config/chromium-flags.conf:",
  "    --proxy-bypass-list=localhost,127.0.0.1,::1",
  "    --proxy-server=http://10.10.10.111:7890",
  "TUN/mihomo:",
  "  mihomo-tun.service: 已停止",
  "  虚拟网卡 Meta: 未创建",
  "  mihomo 配置: 不存在"
].join("\n")

const parsedOn = M.parseStatus(statusOn)
eq(parsedOn.desktop.on, true, "desktop proxy is on")
eq(parsedOn.desktop.endpoint, "10.10.10.111:7890", "desktop endpoint")
eq(parsedOn.git.on, true, "git proxy is on")
eq(parsedOn.git.endpoint, "10.10.10.111:7890", "git endpoint")
eq(parsedOn.sessionEnv, true, "session env file is present")
eq(parsedOn.browser.on, true, "browser flags carry the proxy")
eq(parsedOn.browser.endpoint, "10.10.10.111:7890", "browser endpoint")
eq(parsedOn.tun.service, "stopped", "TUN stopped is parsed")
eq(parsedOn.tun.iface, "", "no TUN interface while stopped")
eq(parsedOn.tun.config, "", "no TUN config while stopped")

const statusDirect = [
  "HTTP   代理: 未启用",
  "git",
  "  http.proxy  = <未设置>",
  "会话环境文件:",
  "  不存在",
  "TUN/mihomo:",
  "  mihomo-tun.service: 运行中",
  "  虚拟网卡 Meta: Meta",
  "  mihomo 配置: /home/alex/.config/mihomo/config.yaml"
].join("\n")

const parsedDirect = M.parseStatus(statusDirect)
eq(parsedDirect.desktop.on, false, "direct desktop proxy")
eq(parsedDirect.git.on, false, "unset git proxy is not on")
eq(parsedDirect.sessionEnv, false, "missing env file is not present")
eq(parsedDirect.browser.on, false, "no browser flags means not proxied")
eq(parsedDirect.tun.service, "running", "running TUN is parsed")
eq(parsedDirect.tun.iface, "Meta", "TUN interface is reported")
has(parsedDirect.tun.config, "config.yaml", "TUN config path is reported")

eq(M.parseStatus("").desktop.on, false, "empty status does not throw")
eq(M.parseStatus(null).tun.service, "unknown", "null status stays unknown")

// --- tools list parsing -----------------------------------------------------
const toolsList = [
  "npm      /home/alex/.npmrc",
  "          https-proxy = http://10.10.10.111:7890",
  "          proxy = http://10.10.10.111:7890",
  "pnpm     /home/alex/.config/pnpm/config.yaml",
  "          httpProxy = http://10.10.10.111:7890",
  "pip      /home/alex/.config/pip/pip.conf",
  "          global.proxy = http://10.10.10.111:7890",
  "cargo    /home/alex/.cargo/config.toml",
  "docker   /home/alex/.docker/config.json",
  "brew     /home/alex/.config/homebrew/brew.env",
  "          http_proxy = http://10.10.10.111:7890"
].join("\n")

const tools = M.parseTools(toolsList)
eq(tools.total, 6, "six tools are listed")
eq(tools.configured, 4, "four carry a proxy")
eq(M.parseTools("").total, 0, "empty tools list")
eq(M.parseTools(null).configured, 0, "null tools list does not throw")

// --- layer rows -------------------------------------------------------------
const rows = M.layerRows(parsedOn, tools)
eq(rows.length, 6, "one row per layer")
eq(rows[0].label, "Desktop proxy", "desktop row")
eq(rows[2].value, "10.10.10.111:7890", "browser row shows the endpoint")
eq(rows[4].value, "4/6 configured", "dev tools row counts")
eq(rows[5].ok, false, "TUN row reflects the stopped service")
eq(M.layerRows(null, tools).length, 0, "no rows without a status")
eq(M.layerRows(parsedDirect, null).length, 5, "tools row is skipped when unknown")

console.log("Model.js: all assertions passed")
